# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedDashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=500, unique=True, verbose_name='Clé de cache')),
                ('cache_type', models.CharField(choices=[('ADMIN_STATS', 'Statistiques admin'), ('AGENT_STATS', 'Statistiques agent'), ('CLIENT_STATS', 'Statistiques client'), ('CONSOMMATION_TRENDS', 'Tendances consommation'), ('FINANCIAL_STATS', 'Statistiques financières'), ('TECHNICAL_STATS', 'Statistiques techniques')], max_length=50, verbose_name='Type de cache')),
                ('data', models.JSONField(verbose_name='Données')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Paramètres requête')),
            ],
            options={
                'verbose_name': 'Donnée cache dashboard',
                'verbose_name_plural': 'Données cache dashboard',
                'db_table': 'cached_dashboard_data',
            },
        ),
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SYSTEM', 'Système')], default='INFO', max_length=20, verbose_name='Type')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='URL action')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name='Libellé action')),
                ('read', models.BooleanField(default=False, verbose_name='Lu')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
            ],
            options={
                'verbose_name': 'Notification tableau de bord',
                'verbose_name_plural': 'Notifications tableaux de bord',
                'db_table': 'dashboard_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardQuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('action_type', models.CharField(choices=[('CREATE_MENAGE', 'Créer ménage'), ('CREATE_COMPTEUR', 'Créer compteur'), ('ENREGISTRER_PAIEMENT', 'Enregistrer paiement'), ('GENERER_FACTURE', 'Générer facture'), ('CONSULTER_CONSO', 'Consulter consommation'), ('ENVOYER_RELANCE', 'Envoyer relance'), ('GENERER_RAPPORT', 'Générer rapport'), ('DIAGNOSTIC_SHELLY', 'Diagnostic Shelly')], max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Couleur')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='Méthode HTTP')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='Requiert confirmation')),
                ('confirmation_message', models.TextField(blank=True, verbose_name='Message confirmation')),
                ('allowed_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent terrain'), ('CLIENT', 'Client'), ('ALL', 'Tous')], max_length=20), blank=True, default=list, size=None, verbose_name='Rôles autorisés')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
            ],
            options={
                'verbose_name': 'Action rapide dashboard',
                'verbose_name_plural': 'Actions rapides dashboard',
                'db_table': 'dashboard_quick_action',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du widget')),
                ('widget_type', models.CharField(choices=[('CONSOMMATION_CHART', 'Graphique consommation'), ('FACTURE_STATUS', 'Statut factures'), ('PAIEMENTS_RECENTS', 'Paiements récents'), ('ALERTES_ACTIVES', 'Alertes actives'), ('STATS_GLOBALES', 'Statistiques globales'), ('MAP_LOCALISATION', 'Carte localisation'), ('PERFORMANCE_AGENT', 'Performance agent'), ('PREDICTION_CONSO', 'Prédiction consommation')], max_length=50, verbose_name='Type de widget')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('default_position', models.JSONField(default=dict, verbose_name='Position par défaut')),
                ('default_size', models.CharField(default='2x2', max_length=20, verbose_name='Taille par défaut')),
                ('allowed_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent terrain'), ('CLIENT', 'Client'), ('ALL', 'Tous')], max_length=20), blank=True, default=list, size=None, verbose_name='Rôles autorisés')),
                ('enabled_by_default', models.BooleanField(default=True, verbose_name='Activé par défaut')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Widget tableau de bord',
                'verbose_name_plural': 'Widgets tableaux de bord',
                'db_table': 'dashboard_widget',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(default=list, verbose_name='Configuration layout')),
                ('theme', models.CharField(default='light', max_length=50, verbose_name='Thème')),
                ('density', models.CharField(default='comfortable', max_length=20, verbose_name='Densité')),
                ('auto_refresh', models.BooleanField(default=True, verbose_name='Rafraîchissement automatique')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='Intervalle rafraîchissement (secondes)')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Dernier accès')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Layout tableau de bord utilisateur',
                'verbose_name_plural': 'Layouts tableaux de bord utilisateurs',
                'db_table': 'user_dashboard_layout',
            },
        ),
        migrations.CreateModel(
            name='UserWidgetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_config', models.JSONField(default=dict, verbose_name='Configuration personnalisée')),
                ('position', models.JSONField(default=dict, verbose_name='Position')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('custom_filters', models.JSONField(default=dict, verbose_name='Filtres personnalisés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Préférence widget utilisateur',
                'verbose_name_plural': 'Préférences widgets utilisateurs',
                'db_table': 'user_widget_preference',
                'ordering': ['order'],
            },
        ),
    ]
