# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheddashboarddata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='dashboardquickaction',
            index=models.Index(fields=['action_type'], name='dashboard_q_action__fffa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardquickaction',
            index=models.Index(fields=['allowed_roles'], name='dashboard_q_allowed_649070_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['widget_type'], name='dashboard_w_widget__9b0ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['allowed_roles'], name='dashboard_w_allowed_985b74_idx'),
        ),
        migrations.AddField(
            model_name='userdashboardlayout',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='userwidgetpreference',
            name='user_dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userdashboardlayout', verbose_name='Dashboard utilisateur'),
        ),
        migrations.AddField(
            model_name='userwidgetpreference',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardwidget', verbose_name='Widget'),
        ),
        migrations.AddField(
            model_name='userdashboardlayout',
            name='enabled_widgets',
            field=models.ManyToManyField(related_name='user_preferences', through='dashboard.UserWidgetPreference', to='dashboard.dashboardwidget', verbose_name='Widgets activés'),
        ),
        migrations.AddIndex(
            model_name='cacheddashboarddata',
            index=models.Index(fields=['cache_key'], name='cached_dash_cache_k_a150c6_idx'),
        ),
        migrations.AddIndex(
            model_name='cacheddashboarddata',
            index=models.Index(fields=['cache_type'], name='cached_dash_cache_t_da17ea_idx'),
        ),
        migrations.AddIndex(
            model_name='cacheddashboarddata',
            index=models.Index(fields=['expires_at'], name='cached_dash_expires_e288e6_idx'),
        ),
        migrations.AddIndex(
            model_name='cacheddashboarddata',
            index=models.Index(fields=['user', 'cache_type'], name='cached_dash_user_id_9add90_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='dashboard_n_user_id_80d8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['notification_type'], name='dashboard_n_notific_47e787_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['expires_at'], name='dashboard_n_expires_be8f17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwidgetpreference',
            unique_together={('user_dashboard', 'widget')},
        ),
    ]
