# Generated by Django 5.2.10 on 2026-01-27 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0, verbose_name='Vues totales')),
                ('total_time_spent', models.IntegerField(default=0, verbose_name='Temps total passé (secondes)')),
                ('avg_session_time', models.IntegerField(default=0, verbose_name='Temps moyen par session (secondes)')),
                ('most_used_widgets', models.JSONField(default=dict, verbose_name='Widgets les plus utilisés')),
                ('most_frequent_actions', models.JSONField(default=dict, verbose_name='Actions les plus fréquentes')),
                ('access_frequency', models.JSONField(default=dict, verbose_name="Fréquence d'accès")),
                ('detected_preferences', models.JSONField(default=dict, verbose_name='Préférences détectées')),
                ('last_access', models.DateTimeField(auto_now=True, verbose_name='Dernier accès')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Analytics dashboard',
                'verbose_name_plural': 'Analytics dashboards',
                'db_table': 'dashboard_analytics',
            },
        ),
        migrations.AlterModelOptions(
            name='dashboardnotification',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Notification tableau de bord', 'verbose_name_plural': 'Notifications tableaux de bord'},
        ),
        migrations.AddField(
            model_name='cacheddashboarddata',
            name='context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Contexte'),
        ),
        migrations.AddField(
            model_name='cacheddashboarddata',
            name='hash',
            field=models.CharField(blank=True, help_text='SHA256 des données pour détecter les changements', max_length=64, verbose_name='Hash des données'),
        ),
        migrations.AddField(
            model_name='cacheddashboarddata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='cacheddashboarddata',
            name='version',
            field=models.CharField(default='1.0', max_length=50, verbose_name='Version des données'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='Accusé réception'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='action_data',
            field=models.JSONField(blank=True, default=dict, verbose_name="Données d'action"),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône FontAwesome (sans le préfixe fa-)", max_length=50, verbose_name='Icône'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='priority',
            field=models.IntegerField(default=0, help_text='0=Normal, 1=Important, 2=Urgent', verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID source'),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='source_module',
            field=models.CharField(blank=True, max_length=100, verbose_name='Module source'),
        ),
        migrations.AddField(
            model_name='dashboardquickaction',
            name='badge_color',
            field=models.CharField(default='danger', max_length=20, verbose_name='Couleur badge'),
        ),
        migrations.AddField(
            model_name='dashboardquickaction',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Texte affiché sur le badge (ex: 'New', 'Hot', etc.)", max_length=20, verbose_name='Texte badge'),
        ),
        migrations.AddField(
            model_name='dashboardquickaction',
            name='category',
            field=models.CharField(blank=True, help_text='Pour regrouper les actions', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='dashboardquickaction',
            name='required_permission',
            field=models.CharField(blank=True, max_length=100, verbose_name='Permission requise'),
        ),
        migrations.AddField(
            model_name='dashboardquickaction',
            name='shortcut_key',
            field=models.CharField(blank=True, help_text="Ex: 'Ctrl+Shift+A'", max_length=50, verbose_name='Raccourci clavier'),
        ),
        migrations.AddField(
            model_name='dashboardquickaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
        migrations.AddField(
            model_name='dashboardquickaction',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='icon',
            field=models.CharField(blank=True, default='chart-line', max_length=50, verbose_name='Icône'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='requires_permission',
            field=models.BooleanField(default=False, verbose_name='Requiert permission spécifique'),
        ),
        migrations.AddField(
            model_name='userdashboardlayout',
            name='default_view',
            field=models.CharField(default='overview', help_text="Vue affichée par défaut lors de l'ouverture", max_length=50, verbose_name='Vue par défaut'),
        ),
        migrations.AddField(
            model_name='userwidgetpreference',
            name='refresh_rate',
            field=models.IntegerField(default=60, verbose_name='Taux de rafraîchissement (secondes)'),
        ),
        migrations.AlterField(
            model_name='cacheddashboarddata',
            name='cache_type',
            field=models.CharField(choices=[('ADMIN_STATS', 'Statistiques admin'), ('AGENT_STATS', 'Statistiques agent'), ('CLIENT_STATS', 'Statistiques client'), ('CONSOMMATION_TRENDS', 'Tendances consommation'), ('FINANCIAL_STATS', 'Statistiques financières'), ('TECHNICAL_STATS', 'Statistiques techniques'), ('WIDGET_DATA', 'Données widget')], max_length=50, verbose_name='Type de cache'),
        ),
        migrations.AlterField(
            model_name='dashboardnotification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SYSTEM', 'Système'), ('ALERT', 'Alerte')], default='INFO', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='dashboardquickaction',
            name='action_type',
            field=models.CharField(choices=[('CREATE_MENAGE', 'Créer ménage'), ('CREATE_COMPTEUR', 'Créer compteur'), ('ENREGISTRER_PAIEMENT', 'Enregistrer paiement'), ('GENERER_FACTURE', 'Générer facture'), ('CONSULTER_CONSO', 'Consulter consommation'), ('ENVOYER_RELANCE', 'Envoyer relance'), ('GENERER_RAPPORT', 'Générer rapport'), ('DIAGNOSTIC_SHELLY', 'Diagnostic Shelly'), ('CREER_ALERTE', 'Créer alerte'), ('ASSIGNER_AGENT', 'Assigner agent'), ('IMPORTER_DATA', 'Importer données')], max_length=50, verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='dashboardquickaction',
            name='color',
            field=models.CharField(default='primary', help_text='Couleur Bootstrap: primary, success, warning, etc.', max_length=20, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='dashboardquickaction',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône FontAwesome (sans le préfixe fa-)", max_length=100, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='dashboardquickaction',
            name='url',
            field=models.CharField(help_text="URL de l'action, peut inclure des variables: {user_id}, {today}, etc.", max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='default_position',
            field=models.JSONField(default=dict, help_text='Format: {x: 0, y: 0, w: 2, h: 2}', verbose_name='Position par défaut'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='default_size',
            field=models.CharField(default='2x2', help_text='1x1, 2x2, 3x2, etc.', max_length=20, verbose_name='Taille par défaut'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('CONSOMMATION_CHART', 'Graphique consommation'), ('FACTURE_STATUS', 'Statut factures'), ('PAIEMENTS_RECENTS', 'Paiements récents'), ('ALERTES_ACTIVES', 'Alertes actives'), ('STATS_GLOBALES', 'Statistiques globales'), ('MAP_LOCALISATION', 'Carte localisation'), ('PERFORMANCE_AGENT', 'Performance agent'), ('PREDICTION_CONSO', 'Prédiction consommation'), ('TASKS_PENDING', 'Tâches en attente'), ('REVENUE_TREND', 'Tendance revenus')], max_length=50, verbose_name='Type de widget'),
        ),
        migrations.AlterField(
            model_name='userdashboardlayout',
            name='density',
            field=models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Confortable'), ('spacious', 'Spacieux')], default='comfortable', max_length=20, verbose_name='Densité'),
        ),
        migrations.AlterField(
            model_name='userdashboardlayout',
            name='layout_config',
            field=models.JSONField(default=list, help_text='Configuration JSON des positions des widgets', verbose_name='Configuration layout'),
        ),
        migrations.AlterField(
            model_name='userdashboardlayout',
            name='refresh_interval',
            field=models.IntegerField(default=300, help_text='En secondes, 300 = 5 minutes', verbose_name='Intervalle rafraîchissement (secondes)'),
        ),
        migrations.AlterField(
            model_name='userdashboardlayout',
            name='theme',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=50, verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='userwidgetpreference',
            name='position',
            field=models.JSONField(default=dict, help_text='Format: {x: 0, y: 0, w: 2, h: 2}', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='userwidgetpreference',
            name='user_dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_preferences', to='dashboard.userdashboardlayout', verbose_name='Dashboard utilisateur'),
        ),
        migrations.AlterField(
            model_name='userwidgetpreference',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='dashboard.dashboardwidget', verbose_name='Widget'),
        ),
        migrations.AddIndex(
            model_name='cacheddashboarddata',
            index=models.Index(fields=['created_at'], name='cached_dash_created_226dca_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['priority'], name='dashboard_n_priorit_3b12b5_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['source_module', 'source_id'], name='dashboard_n_source__58ead4_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardquickaction',
            index=models.Index(fields=['enabled', 'visible'], name='dashboard_q_enabled_3c83de_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardquickaction',
            index=models.Index(fields=['category'], name='dashboard_q_categor_f42260_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['enabled_by_default'], name='dashboard_w_enabled_d26f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userdashboardlayout',
            index=models.Index(fields=['user'], name='user_dashbo_user_id_1e802f_idx'),
        ),
        migrations.AddIndex(
            model_name='userdashboardlayout',
            index=models.Index(fields=['last_accessed'], name='user_dashbo_last_ac_c4fcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='userwidgetpreference',
            index=models.Index(fields=['user_dashboard', 'enabled'], name='user_widget_user_da_e09b7a_idx'),
        ),
        migrations.AddField(
            model_name='dashboardanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_analytics', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='dashboardanalytics',
            index=models.Index(fields=['user', 'last_access'], name='dashboard_a_user_id_d50aa8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardanalytics',
            unique_together={('user',)},
        ),
    ]
