# Generated by Django 5.2.10 on 2026-04-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboardanalytics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedDashboardData',
        ),
    ]
