# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('index_debut_periode', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_fin_periode', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phase_1_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase_2_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase_3_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puissance_max_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('puissance_moyenne_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('facture_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('details_journaliers', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('SHELLY_AUTO', 'Shelly automatique'), ('RELEVE_MANUEL', 'Relevé manuel'), ('ESTIMATION', 'Estimation'), ('CORRIGE', 'Corrigé')], default='SHELLY_AUTO', max_length=20)),
                ('shelly_device_id', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDÉ', 'Validé'), ('FACTURÉ', 'Facturé'), ('ANOMALIE', 'Anomalie')], default='BROUILLON', max_length=20)),
                ('anomalie', models.TextField(blank=True)),
                ('date_releve', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='compteurs.compteur')),
            ],
            options={
                'db_table': 'consommation',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=30, unique=True)),
                ('periode', models.DateField()),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('consommation_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_consommation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_abonnement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_taux', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('redevance_communale', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('autres_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ÉMISE', 'Émise'), ('PARTIELLEMENT_PAYÉE', 'Partiellement payée'), ('PAYÉE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_facturation', to='compteurs.compteur')),
                ('consommation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture_facturation', to='consommation.consommation')),
            ],
            options={
                'db_table': 'facture_facturation',
            },
        ),
    ]
