# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consommation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consommation',
            index=models.Index(fields=['periode'], name='consommatio_periode_24e156_idx'),
        ),
        migrations.AddIndex(
            model_name='consommation',
            index=models.Index(fields=['statut'], name='consommatio_statut_db4aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='consommation',
            index=models.Index(fields=['source'], name='consommatio_source_a3a3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='consommation',
            index=models.Index(fields=['compteur', 'periode'], name='consommatio_compteu_0eae54_idx'),
        ),
        migrations.AddConstraint(
            model_name='consommation',
            constraint=models.UniqueConstraint(fields=('compteur', 'periode'), name='uk_consommation_compteur_periode'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut'], name='facture_fac_statut_ebe088_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_echeance'], name='facture_fac_date_ec_11537b_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero_facture'], name='facture_fac_numero__eb9fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['compteur', 'periode'], name='facture_fac_compteu_ba23b6_idx'),
        ),
    ]
