# Generated by Django 5.2.10 on 2026-01-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consommation', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
