# Generated by Django 5.2.10 on 2026-01-27 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteurs', '0002_initial'),
        ('consommation', '0003_delete_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.CreateModel(
            name='AnomalieConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(choices=[('CONSO_ABERRANTE', 'Consommation aberrante'), ('INDEX_NEGATIF', 'Index négatif'), ('DOUBLON', 'Doublon détecté'), ('ECART_IMPORTANT', 'Écart important avec période précédente'), ('FORMAT_INVALIDE', 'Format de données invalide')], max_length=50)),
                ('severite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], max_length=20)),
                ('description', models.TextField()),
                ('donnees_analysees', models.JSONField()),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('resolue', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('consommation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomalie_detail', to='consommation.consommation')),
                ('detectee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_resolues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalie consommation',
                'verbose_name_plural': 'Anomalies consommation',
                'db_table': 'anomalie_consommation',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('VALIDATE', 'Validation'), ('CORRECT', 'Correction'), ('MARK_ANOMALY', 'Marquage anomalie')], max_length=20)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consommation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='consommation.consommation')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique consommation',
                'verbose_name_plural': 'Historiques consommation',
                'db_table': 'historique_consommation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsommationJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('consommation_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consommation (kWh)')),
                ('puissance_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Puissance max (W)')),
                ('source', models.CharField(choices=[('SHELLY', 'Capteur Shelly'), ('ESTIMATION', 'Estimation'), ('MANUEL', 'Saisie manuelle')], default='SHELLY', max_length=50, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations_journalieres', to='compteurs.compteur', verbose_name='Compteur')),
            ],
            options={
                'verbose_name': 'Consommation journalière',
                'verbose_name_plural': 'Consommations journalières',
                'db_table': 'consommation_journaliere',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['compteur', 'date'], name='consommatio_compteu_4d9a72_idx'), models.Index(fields=['date'], name='consommatio_date_15bdad_idx')],
                'unique_together': {('compteur', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ConsommationQuotidienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consommation_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puissance_max_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('puissance_moyenne_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heures_pleines', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heures_creuses', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('consommation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_quotidiens', to='consommation.consommation')),
            ],
            options={
                'verbose_name': 'Consommation quotidienne',
                'verbose_name_plural': 'Consommations quotidiennes',
                'db_table': 'consommation_quotidienne',
                'indexes': [models.Index(fields=['date'], name='consommatio_date_f5a9be_idx')],
                'unique_together': {('consommation', 'date')},
            },
        ),
    ]
