# Generated by Django 5.2.10 on 2026-04-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consommation', '0004_consommation_notes_anomalieconsommation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsommationQuotidienne',
        ),
    ]
