# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('nombre_phase', models.IntegerField(default=1)),
                ('calibre_courant', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calibration_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=6)),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ERREUR', 'Erreur')], default='ACTIF', max_length=20)),
                ('derniere_communication', models.DateTimeField(blank=True, null=True)),
                ('puissance_instantanee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('energie_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_installation', models.DateTimeField(auto_now_add=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('derniere_mise_a_jour', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capteur',
            },
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=30, unique=True)),
                ('matricule_compteur', models.CharField(max_length=30, unique=True)),
                ('numero_client', models.CharField(blank=True, max_length=20)),
                ('type_compteur', models.CharField(choices=[('ELECTRONIQUE', 'Électronique'), ('MECANIQUE', 'Mécanique'), ('INTELLIGENT', 'Intelligent'), ('PREPAYE', 'Prépayé')], default='ELECTRONIQUE', max_length=20)),
                ('puissance_souscrite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tension', models.CharField(choices=[('BT_220V', 'BT 220V'), ('BT_380V', 'BT 380V'), ('MT', 'Moyenne Tension'), ('HT', 'Haute Tension')], default='BT_220V', max_length=20)),
                ('phase', models.CharField(choices=[('MONOPHASE', 'Monophasé'), ('TRIPHASE', 'Triphasé')], default='MONOPHASE', max_length=20)),
                ('adresse_installation', models.TextField(blank=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('reference_local', models.CharField(blank=True, max_length=100)),
                ('date_installation', models.DateField()),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('periode_facturation', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('BIMENSUEL', 'Bimensuel')], default='MENSUEL', max_length=20)),
                ('jour_releve', models.IntegerField(default=25)),
                ('jour_paiement', models.IntegerField(default=10)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu'), ('COUPE', 'Coupé'), ('RESILIE', 'Résilié'), ('EN_PANNE', 'En panne')], default='ACTIF', max_length=20)),
                ('index_initial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('index_actuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shelly_device_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('shelly_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('shelly_status', models.CharField(choices=[('CONNECTE', 'Connecté'), ('DECONNECTE', 'Déconnecté'), ('ERREUR', 'Erreur')], default='DECONNECTE', max_length=20)),
                ('derniere_sync_shelly', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.localite')),
            ],
            options={
                'db_table': 'compteur',
            },
        ),
    ]
