# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compteurs', '0001_initial'),
        ('menages', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='menage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='menages.menage'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='type_tarification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.typetarification'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='compteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='compteurs.compteur'),
        ),
        migrations.AddIndex(
            model_name='compteur',
            index=models.Index(fields=['numero_contrat'], name='compteur_numero__3b4202_idx'),
        ),
        migrations.AddIndex(
            model_name='compteur',
            index=models.Index(fields=['matricule_compteur'], name='compteur_matricu_2229e2_idx'),
        ),
        migrations.AddIndex(
            model_name='compteur',
            index=models.Index(fields=['statut'], name='compteur_statut_bc6416_idx'),
        ),
        migrations.AddIndex(
            model_name='compteur',
            index=models.Index(fields=['menage'], name='compteur_menage__283ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='compteur',
            index=models.Index(fields=['shelly_status'], name='compteur_shelly__eef631_idx'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['device_id'], name='capteur_device__9b1890_idx'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['compteur'], name='capteur_compteu_f2874d_idx'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['status'], name='capteur_status_15c352_idx'),
        ),
    ]
