# Generated by Django 5.2.10 on 2026-02-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteurs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCompteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('technologie', models.CharField(choices=[('ELECTRONIQUE', 'Électronique'), ('MECANIQUE', 'Mécanique'), ('INTELLIGENT', 'Intelligent (Smart Meter)'), ('PREPAYE', 'Prépayé'), ('HYBRIDE', 'Hybride')], default='ELECTRONIQUE', max_length=20)),
                ('tension_compatibilite', models.CharField(default='BT_220V', max_length=20)),
                ('nombre_phases', models.IntegerField(choices=[(1, 'Monophasé'), (3, 'Triphasé')], default=1)),
                ('compatible_shelly', models.BooleanField(default=True)),
                ('prix_unitaire_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('en_stock', models.BooleanField(default=True)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'type_compteur',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.RemoveField(
            model_name='compteur',
            name='type_compteur',
        ),
        migrations.AddField(
            model_name='compteur',
            name='type_compteur_detail',
            field=models.ForeignKey(blank=True, help_text='Type de compteur détaillé', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compteurs', to='compteurs.typecompteur'),
        ),
    ]
