# Generated by Django 5.2.10 on 2026-04-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteurs', '0003_typecompteur_remove_compteur_type_compteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='date_reset_shelly',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compteur',
            name='dernier_index_shelly',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='compteur',
            name='shelly_offset',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
