# Generated by Django 5.2.10 on 2026-02-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('parametrage', '0007_configurationtarifaire_taxetarifaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureconsommation',
            name='taxes_appliquees',
            field=models.JSONField(default=dict, help_text='Snapshot des taxes au moment de la facturation', verbose_name='Taxes appliquées'),
        ),
        migrations.AddField(
            model_name='factureconsommation',
            name='type_tarification',
            field=models.ForeignKey(help_text='La grille tarifaire utilisée pour cette facture', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='parametrage.typetarification', verbose_name='Type de tarification appliqué'),
        ),
    ]
