# Generated by Django 5.2.10 on 2026-03-27 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_factureconsommation_taxes_appliquees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_generation_factures', models.DateField(blank=True, null=True, verbose_name='Date génération factures')),
                ('date_echeance_default', models.IntegerField(default=14, help_text="Nombre de jours après l'émission pour l'échéance", verbose_name='Échéance par défaut (jours)')),
            ],
            options={
                'verbose_name': 'Période de facturation',
                'verbose_name_plural': 'Périodes de facturation',
                'db_table': 'periode_facturation',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['actif'], name='periode_fac_actif_d6ed99_idx'), models.Index(fields=['date_debut', 'date_fin'], name='periode_fac_date_de_4e248a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DossierImpaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant dû')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date résolution')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_impayes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_impayes', to='facturation.factureconsommation', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Dossier impayé',
                'verbose_name_plural': 'Dossiers impayés',
                'db_table': 'dossier_impaye',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['facture'], name='dossier_imp_facture_a9bce3_idx'), models.Index(fields=['client'], name='dossier_imp_client__605ac5_idx'), models.Index(fields=['statut'], name='dossier_imp_statut_4b6fb1_idx')],
            },
        ),
    ]
