# Generated by Django 5.2.10 on 2026-04-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_periodefacturation_dossierimpaye'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenaliteRetard',
        ),
        migrations.DeleteModel(
            name='Remise',
        ),
    ]
