# Generated by Django 5.2.10 on 2026-01-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('CONSOMMATION_ANORMALE', 'Consommation anormale'), ('CONSOMMATION_NULLE', 'Consommation nulle'), ('PIC_DE_CONSOMMATION', 'Pic de consommation'), ('CAPTEUR_DECONNECTE', 'Capteur déconnecté'), ('PAIEMENT_EN_RETARD', 'Paiement en retard'), ('ANOMALIE_TECHNIQUE', 'Anomalie technique'), ('DEPASSEMENT_PUISSANCE', 'Dépassement puissance')], max_length=50)),
                ('message', models.TextField()),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITIQUE', 'Critique')], default='WARNING', max_length=20)),
                ('valeur_mesuree', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valeur_seuil', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('destinataire_role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent'), ('CLIENT', 'Client')], max_length=20)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('LU', 'Lue'), ('TRAITEE', 'Traitée'), ('IGNOREE', 'Ignorée')], default='ACTIVE', max_length=20)),
                ('notes_traitement', models.TextField(blank=True)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerte',
            },
        ),
        migrations.CreateModel(
            name='RegleAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_alerte', models.CharField(choices=[('CONSOMMATION_ANORMALE', 'Consommation anormale'), ('CONSOMMATION_NULLE', 'Consommation nulle'), ('PIC_DE_CONSOMMATION', 'Pic de consommation'), ('CAPTEUR_DECONNECTE', 'Capteur déconnecté'), ('PAIEMENT_EN_RETARD', 'Paiement en retard'), ('ANOMALIE_TECHNIQUE', 'Anomalie technique'), ('DEPASSEMENT_PUISSANCE', 'Dépassement puissance')], max_length=50)),
                ('seuil', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'regle_alerte',
            },
        ),
    ]
