# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0001_initial'),
        ('compteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='compteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compteurs.compteur'),
        ),
    ]
