# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0002_initial'),
        ('consommation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='consommation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='consommation.consommation'),
        ),
    ]
