# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['statut'], name='alerte_statut_22029f_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['type_alerte'], name='alerte_type_al_b7812a_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['date_detection'], name='alerte_date_de_c57fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['consommation'], name='alerte_consomm_fd9364_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['compteur', 'statut'], name='alerte_compteu_fbbba9_idx'),
        ),
    ]
