# Generated by Django 5.2.10 on 2026-03-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='notifications_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de notifications'),
        ),
    ]
