# Generated by Django 5.2.10 on 2026-04-16 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0005_alerte_notifications_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='regle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='alertes.reglealerte'),
        ),
    ]
