# Generated by Django 5.2.10 on 2026-01-29 00:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_paiement', models.CharField(max_length=100, unique=True, verbose_name='Référence paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE_BANCAIRE', 'Carte bancaire'), ('CHEQUE', 'Chèque'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('REJETÉ', 'Rejeté'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateTimeField(verbose_name='Date paiement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date validation')),
                ('reference_externe', models.CharField(blank=True, max_length=100, verbose_name='Référence externe')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('fichier_justificatif', models.FileField(blank=True, null=True, upload_to='paiements/justificatifs/', verbose_name='Fichier justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.factureconsommation', verbose_name='Facture')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('raison', models.TextField(blank=True, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date changement')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='paiements.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Historique statut paiement',
                'verbose_name_plural': 'Historiques statut paiement',
                'db_table': 'historique_statut_paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraisTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('COMMISSION_BANCAIRE', 'Commission bancaire'), ('FRAIS_MOBILE_MONEY', 'Frais Mobile Money'), ('TAXE_GOUVERNEMENTALE', 'Taxe gouvernementale'), ('FRAIS_PLATEFORME', 'Frais plateforme'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type frais')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('facture_frais', models.FileField(blank=True, null=True, upload_to='paiements/frais/', verbose_name='Facture frais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='paiements.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Frais transaction',
                'verbose_name_plural': 'Frais transactions',
                'db_table': 'frais_transaction',
            },
        ),
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux commission (%)')),
                ('montant_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant commission')),
                ('statut', models.CharField(choices=[('DUE', 'Due'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='DUE', max_length=20, verbose_name='Statut commission')),
                ('date_paiement_commission', models.DateField(blank=True, null=True, verbose_name='Date paiement commission')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='paiements.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Commission agent',
                'verbose_name_plural': 'Commissions agents',
                'db_table': 'commission_agent',
            },
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference_paiement'], name='paiement_referen_e52df9_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='paiement_statut_a0acf1_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='paiement_date_pa_f31e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture'], name='paiement_facture_4b9c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquestatutpaiement',
            index=models.Index(fields=['paiement'], name='historique__paiemen_32af5f_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquestatutpaiement',
            index=models.Index(fields=['created_at'], name='historique__created_b1686c_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionagent',
            index=models.Index(fields=['agent'], name='commission__agent_i_0b9331_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionagent',
            index=models.Index(fields=['statut'], name='commission__statut_99d752_idx'),
        ),
    ]
