# Generated by Django 5.2.10 on 2026-04-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraistransaction',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='historiquestatutpaiement',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='historiquestatutpaiement',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='CommissionAgent',
        ),
        migrations.DeleteModel(
            name='FraisTransaction',
        ),
        migrations.DeleteModel(
            name='HistoriqueStatutPaiement',
        ),
    ]
