# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_menage', models.CharField(max_length=100)),
                ('reference_menage', models.CharField(max_length=30, unique=True)),
                ('adresse_complete', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('precision_gps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_geolocalisation', models.CharField(choices=[('GPS_AGENT', 'GPS Agent'), ('GOOGLE_MAPS', 'Google Maps'), ('SAISIE_MANUEL', 'Saisie manuelle')], default='GPS_AGENT', max_length=20)),
                ('google_place_id', models.CharField(blank=True, max_length=255)),
                ('adresse_google', models.TextField(blank=True)),
                ('nombre_personnes', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('type_habitation', models.CharField(choices=[('MAISON', 'Maison'), ('APPARTEMENT', 'Appartement'), ('VILLA', 'Villa'), ('BANCO', 'Banco'), ('AUTRE', 'Autre')], default='MAISON', max_length=20)),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20)),
                ('email_secondaire', models.EmailField(blank=True, max_length=254)),
                ('personne_contact', models.CharField(blank=True, max_length=100)),
                ('categorie_socio_professionnelle', models.CharField(blank=True, max_length=50)),
                ('revenu_mensuel_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('point_repere', models.TextField(blank=True)),
                ('code_acces', models.CharField(blank=True, max_length=100)),
                ('instructions_livraison', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('DEMENAGE', 'Déménagé')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.localite')),
            ],
            options={
                'db_table': 'menage',
            },
        ),
    ]
