# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menage',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='menage',
            index=models.Index(fields=['reference_menage'], name='menage_referen_123300_idx'),
        ),
        migrations.AddIndex(
            model_name='menage',
            index=models.Index(fields=['statut'], name='menage_statut_86cee0_idx'),
        ),
        migrations.AddIndex(
            model_name='menage',
            index=models.Index(fields=['utilisateur'], name='menage_utilisa_3616e2_idx'),
        ),
        migrations.AddIndex(
            model_name='menage',
            index=models.Index(fields=['localite'], name='menage_localit_6b378b_idx'),
        ),
    ]
