# Generated by Django 5.2.10 on 2026-02-13 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menages', '0003_combined_type_habitation_migration'),
        ('parametrage', '0006_populate_typehabitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menage',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AGENT_TERRAIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menages_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menage',
            name='type_habitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menages', to='parametrage.typehabitation'),
        ),
    ]
