# Generated by Django 5.2.10 on 2026-03-05 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menages', '0004_menage_agent_alter_menage_type_habitation'),
        ('parametrage', '0007_configurationtarifaire_taxetarifaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'agence")),
                ('pays', models.CharField(default='Congo-Brazzaville', max_length=100, verbose_name='Pays')),
                ('societe', models.CharField(default='Energie Electrique du Congo', editable=False, max_length=100, verbose_name='Société')),
                ('code_agence', models.CharField(max_length=20, unique=True, verbose_name='Code agence')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agences', to='parametrage.departement', verbose_name='Département')),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agences', to='parametrage.localite', verbose_name='Localité')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'db_table': 'agence',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='menage',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menages', to='menages.agence', verbose_name='Agence'),
        ),
    ]
