# Generated by Django 5.2.10 on 2026-03-05 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menages', '0005_agence_menage_agence'),
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='menages.agence', verbose_name='Agence'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['agence'], name='utilisateur_agence__f52a72_idx'),
        ),
    ]
