# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditarchive',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='auditpolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur source'),
        ),
        migrations.AddIndex(
            model_name='auditarchive',
            index=models.Index(fields=['archived_at'], name='audit_archi_archive_55bace_idx'),
        ),
        migrations.AddIndex(
            model_name='auditarchive',
            index=models.Index(fields=['start_date', 'end_date'], name='audit_archi_start_d_9a1cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_log_timesta_e8e14e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_log_user_id_4dac76_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity'], name='audit_log_severit_33a46a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity__c2633a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['success'], name='audit_log_success_fd34e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_ip'], name='audit_log_user_ip_26e269_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['generated_at'], name='audit_repor_generat_a59214_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['report_type'], name='audit_repor_report__c02994_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['generated_by'], name='audit_repor_generat_c86fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['status'], name='audit_repor_status_965184_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['detected_at'], name='security_ev_detecte_f98663_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type'], name='security_ev_event_t_b3c533_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity'], name='security_ev_severit_dfa400_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['source_ip'], name='security_ev_source__b2c990_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['blocked'], name='security_ev_blocked_8d7ef4_idx'),
        ),
    ]
