# Generated by Django 5.2.10 on 2026-04-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
    ]
