# Generated by Django 5.2.10 on 2026-01-24 00:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_departement', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('polygone', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('centre_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('centre_longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departement',
            },
        ),
        migrations.CreateModel(
            name='TypeTarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIEL', 'Industriel'), ('ADMINISTRATIF', 'Administratif'), ('SPECIAL', 'Spécial')], max_length=20)),
                ('tranches', models.JSONField()),
                ('abonnement_mensuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('reference_arrete', models.CharField(blank=True, max_length=100)),
                ('date_effet', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'type_tarification',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('type_localite', models.CharField(choices=[('VILLE', 'Ville'), ('COMMUNE', 'Commune'), ('QUARTIER', 'Quartier'), ('VILLAGE', 'Village')], default='QUARTIER', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('google_place_id', models.CharField(blank=True, max_length=255)),
                ('zone_rayon_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.departement')),
            ],
            options={
                'db_table': 'localite',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='localite_latitud_5d57c3_idx'), models.Index(fields=['google_place_id'], name='localite_google__2fb06f_idx')],
            },
        ),
    ]
