# Generated by Django 5.2.10 on 2026-01-31 12:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0002_alter_departement_options_alter_localite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typetarification',
            options={'ordering': ['-date_effet', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['nom'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='zone',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 31, 12, 28, 31, 915211, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localite',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='localite',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localites', to='parametrage.departement'),
        ),
        migrations.AlterField(
            model_name='localite',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localite',
            name='zone_rayon_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='reference_arrete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='tranches',
            field=models.JSONField(default=list, help_text="Liste de dictionnaires: [{'min': 0, 'max': 50, 'prix_kwh': 150}, ...]"),
        ),
        migrations.AlterField(
            model_name='zone',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parametrage.departement'),
        ),
        migrations.AlterModelTable(
            name='zone',
            table='zone',
        ),
    ]
