# Generated by Django 5.2.10 on 2026-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0003_alter_typetarification_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localite',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
