# Generated by Django 5.2.10 on 2026-02-12 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0004_localite_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHabitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('VILLA', 'Villa'), ('APPARTEMENT', 'Appartement'), ('STUDIO', 'Studio'), ('MAISON_TRADITIONNELLE', 'Maison traditionnelle'), ('IMMEUBLE', 'Immeuble'), ('COMMERCE', 'Commerce'), ('MIXTE', 'Mixte (Habitation + Commerce)')], default='APPARTEMENT', max_length=30)),
                ('standing', models.CharField(choices=[('ECONOMIQUE', 'Économique'), ('MOYEN', 'Moyen'), ('STANDING', 'Standing'), ('HAUT_STANDING', 'Haut standing')], default='MOYEN', max_length=20)),
                ('surface_moyenne_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nombre_pieces_moyen', models.IntegerField(blank=True, null=True)),
                ('consommation_estimee_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('caracteristiques', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_tarification_recommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_habitation', to='parametrage.typetarification')),
            ],
            options={
                'verbose_name': "Type d'habitation",
                'verbose_name_plural': "Types d'habitation",
                'db_table': 'type_habitation',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
    ]
