# Generated by Django 5.2.10 on 2026-02-24 15:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0006_populate_typehabitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(default='Congo-Brazzaville', max_length=100, verbose_name='Pays')),
                ('timbre_electronique', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Timbre électronique (FCFA)')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Configuration tarifaire',
                'verbose_name_plural': 'Configurations tarifaires',
                'db_table': 'configuration_tarifaire',
                'ordering': ['pays', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TaxeTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: RAV, CA, TIMBRE', max_length=20, verbose_name='Code taxe')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la taxe')),
                ('type_taxe', models.CharField(choices=[('FIXE', 'Montant fixe'), ('POURCENTAGE', 'Pourcentage')], default='FIXE', max_length=20, verbose_name='Type de taxe')),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant fixe (FCFA)')),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage (%)')),
                ('base_calcul', models.CharField(choices=[('HT', 'Sur le total HT'), ('CONSO', 'Sur la consommation'), ('ABONNEMENT', "Sur l'abonnement"), ('TTC', 'Sur le total TTC')], default='HT', max_length=20, verbose_name='Base de calcul')),
                ('soumis_tva', models.BooleanField(default=False, help_text="Cette taxe est-elle incluse dans l'assiette de la TVA ?", verbose_name='Soumis à TVA')),
                ('ordre_application', models.PositiveIntegerField(default=0, verbose_name="Ordre d'application")),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Taxe tarifaire',
                'verbose_name_plural': 'Taxes tarifaires',
                'db_table': 'taxe_tarifaire',
                'ordering': ['tarification', 'ordre_application'],
            },
        ),
        migrations.CreateModel(
            name='TrancheTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borne_inferieure', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Borne inférieure (kWh)')),
                ('borne_superieure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Borne supérieure (kWh)')),
                ('prix_kwh', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix du kWh (FCFA)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'application")),
            ],
            options={
                'verbose_name': 'Tranche tarifaire',
                'verbose_name_plural': 'Tranches tarifaires',
                'db_table': 'tranche_tarifaire',
                'ordering': ['tarification', 'ordre', 'borne_inferieure'],
            },
        ),
        migrations.AlterModelOptions(
            name='typetarification',
            options={'ordering': ['-date_effet', 'nom'], 'verbose_name': 'Type de tarification', 'verbose_name_plural': 'Types de tarification'},
        ),
        migrations.RemoveField(
            model_name='typetarification',
            name='tranches',
        ),
        migrations.AddField(
            model_name='typetarification',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='typetarification',
            name='periodicite',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('BIMESTRIEL', 'Bimestriel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel')], default='BIMESTRIEL', max_length=20, verbose_name='Périodicité de facturation'),
        ),
        migrations.AddField(
            model_name='typetarification',
            name='tva_taux',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux TVA (%)'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='abonnement_mensuel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Abonnement mensuel (FCFA)'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='categorie',
            field=models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIEL', 'Industriel'), ('ADMINISTRATIF', 'Administratif'), ('SPECIAL', 'Spécial')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name="Conditions d'application"),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='date_effet',
            field=models.DateField(verbose_name="Date d'effet"),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='devise',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='typetarification',
            name='reference_arrete',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence arrêté/loi'),
        ),
        migrations.AddIndex(
            model_name='typetarification',
            index=models.Index(fields=['code'], name='type_tarifi_code_ba0f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='typetarification',
            index=models.Index(fields=['categorie', 'actif'], name='type_tarifi_categor_cdcecd_idx'),
        ),
        migrations.AddIndex(
            model_name='typetarification',
            index=models.Index(fields=['date_effet', 'date_fin'], name='type_tarifi_date_ef_1f8b16_idx'),
        ),
        migrations.AddField(
            model_name='configurationtarifaire',
            name='tarification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='parametrage.typetarification'),
        ),
        migrations.AddField(
            model_name='taxetarifaire',
            name='tarification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='parametrage.typetarification'),
        ),
        migrations.AddField(
            model_name='tranchetarifaire',
            name='tarification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='parametrage.typetarification'),
        ),
        migrations.AlterUniqueTogether(
            name='taxetarifaire',
            unique_together={('tarification', 'code')},
        ),
        migrations.AddIndex(
            model_name='tranchetarifaire',
            index=models.Index(fields=['tarification', 'ordre'], name='tranche_tar_tarific_7e38c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tranchetarifaire',
            unique_together={('tarification', 'borne_inferieure'), ('tarification', 'ordre')},
        ),
    ]
